Chore(ci): Check for the clean working directory after the build
  * we sometimes forget to built and commit an exporter build
  * this stops publishing of the packages because of dirty working directory

diff --git a/.github/workflows/build.yaml b/.github/workflows/build.yaml
--- a/.github/workflows/build.yaml
+++ b/.github/workflows/build.yaml
@@ -45,3 +45,11 @@ jobs:
 
       - name: Build packages
         run: yarn build
+
+      - name: Check for clean working directory
+        run: |
+          if [[ -n "$(git status --porcelain)" ]]; then
+            echo "Error: Git working directory is not clean"
+            git status
+            exit 1
+          fi
